### ISSUE TITLE
Absenteeism not working in Graffana

### ISSUE THREAD

**Issue by Kingbadger3d** [intel-iot-devkit/intelligent-classroom#6]
Hi again,

Data for absenteeism is still not working in dash, Also AI accuracy is far worse than shown in Intels video demonstrations. With the latest version it only detects the front two pupils sitting in the classroom. Ill do a video and post to show the issue.

**Comment by Kingbadger3d** [comment]
Quick Video grab of runing the demo and the bad results:

https://youtu.be/5GcR6nym7Is

I did a video of the sample running on R1.1 which still was not working as should, but gave better results than this version:

https://youtu.be/07QdEA4VHMU

**Comment by meera2019** [comment]
Hi,
•	We can only see Absentee count once after 30mins of class start.
For ex: Class started 9 AM, we show absentee list as 0, at 9:30 we show the count of absentees which are not available(not matched in gallery reference data) and not recognized in the video.

•	The video which was used in the current release(Openvino_R3) is having dimensions of 1920X1080 due to this it was unable to detect all the people in the video. (Some times we can see one guy is standing instead of sitting due to the model issues.) 
•	The video which was used in earlier (Openvino_R1) is having dimensions of 1060X510 and it is working fine.
•	We would like to handle the current video dimensions 1920X1080  as well in the next release.
Note : Added one more new image in the gallery and updated timetable.txt file to display the absentees list in Grafana. please take the latest code and follow the above steps to see the absentees in Grafana

**Comment by meera2019** [comment]
issues is resolved
